/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymm;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author amnassar
 */
public final class pay extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
     Connection con ;
     PreparedStatement pst ;
     ResultSet rs;
     int count;
     public String y ;
     public String datee;
     public  Calendar cal;
     String dayyy ;
    
   
    public pay( )throws IOException {
        initComponents();
        con=DBConnect.connect();
        sports();
        comboxfromcombo1();comboxfromcombo2();
          TableCellRenderer rendererFromHeader = tdetails.getTableHeader().getDefaultRenderer();
JLabel headerLabel = (JLabel) rendererFromHeader;
headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tdetails.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(6).setCellRenderer( centerRenderer );
          cal = new GregorianCalendar();
             
                int month=cal.get(Calendar.MONTH)+1;
             int year = cal.get(Calendar.YEAR);
                 int dayy =cal.get(Calendar.DAY_OF_MONTH);
             dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
           date1.setText(year+"-"+month+"-"+dayyy);
           datee=date1.getText().toString();
           ((JTextField)from.getDateEditor().getUiComponent()).setText(datee);
            tablelord();
            
  
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        days = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        to = new com.toedter.calendar.JDateChooser();
        from = new com.toedter.calendar.JDateChooser();
        cmsport = new javax.swing.JComboBox();
        price = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        save3 = new javax.swing.JButton();
        cmtype = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        serial = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        save1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdetails.setBackground(new java.awt.Color(138, 203, 195));
        tdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial", "Name", "Sport", "Type", "Price", "From", "To"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(0).setMinWidth(100);
            tdetails.getColumnModel().getColumn(0).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(0).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(2).setMinWidth(150);
            tdetails.getColumnModel().getColumn(2).setPreferredWidth(150);
            tdetails.getColumnModel().getColumn(2).setMaxWidth(150);
            tdetails.getColumnModel().getColumn(3).setMinWidth(80);
            tdetails.getColumnModel().getColumn(3).setPreferredWidth(80);
            tdetails.getColumnModel().getColumn(3).setMaxWidth(80);
            tdetails.getColumnModel().getColumn(4).setMinWidth(100);
            tdetails.getColumnModel().getColumn(4).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 920, 260));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setText("Exception day");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 150, -1));

        days.setEditable(false);
        days.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        days.setText("0");
        jPanel10.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 60, 30));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setText("Price");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 110, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setText("From");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("To");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, -1));

        to.setDateFormatString("yyyy-MM-dd");
        jPanel10.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, 30));

        from.setDateFormatString("yyyy-M-dd");
        jPanel10.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 30));

        cmsport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel10.add(cmsport, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, 30));

        price.setEditable(false);
        price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 80, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Sport");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        save3.setBackground(new java.awt.Color(138, 203, 195));
        save3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save3.setText("Clear");
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });
        jPanel10.add(save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 120, 50));

        cmtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Month", "Half month" }));
        jPanel10.add(cmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 210, 30));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("Type");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 110, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("Phone");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 110, -1));

        phone.setEditable(false);
        phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 210, 30));

        name.setEditable(false);
        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 210, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Name");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, -1));

        serial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        serial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serialKeyPressed(evt);
            }
        });
        jPanel10.add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setText("Serial");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, -1));

        save1.setBackground(new java.awt.Color(138, 203, 195));
        save1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save1.setText("Save");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel10.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 130, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        date1.setText("jLabel1");
        jPanel10.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
      String seriall = serial.getText();
      String namee = name.getText();
      String phonee =phone.getText();
      String fromm= ((JTextField)from.getDateEditor().getUiComponent()).getText();
      String too= ((JTextField)to.getDateEditor().getUiComponent()).getText();
      String pricee= price.getText();
      String sportt=cmsport.getSelectedItem().toString();
      String typee=cmtype.getSelectedItem().toString();
      TimeZone tz = TimeZone.getTimeZone("GMT+02");
             Calendar c = Calendar.getInstance(tz);
             String time = String.format("%02d" , c.get(Calendar.HOUR_OF_DAY))+":"+
                     String.format("%02d" , c.get(Calendar.MINUTE));
             String fulldatee=datee+" "+time;
      
      try{
                        String sql = "INSERT INTO gym.pay (name,serial,phone,fromm, too,amount,sport,type,date,date1) VALUES"
                        + " ('"+namee+"','"+seriall+"','"+phonee+"','"+fromm+"','"+too+"','"+pricee+"','"+sportt+"','"+typee+"','"+fulldatee+"','"+datee+"')";
                        pst = (PreparedStatement)con.prepareStatement(sql);
                        pst.execute();
                        String sqla = "INSERT INTO gym.money (serial,name,sport,date,fulldate,type,amount,fromm,too) VALUES"
                     + " ('"+seriall+"','"+namee+"','"+sportt+"','"+datee+"','"+fulldatee+"','"+typee+"','"+price.getText()+"','"+fromm+"','"+too+"')";
                         String sqll4 = "INSERT INTO gym.logs (type,serial,name,amount,date,fulldate) VALUES\n" +
" ('"+typee+"','"+seriall+"','"+namee+"','"+pricee+"','"+datee+"','"+fulldatee+"')";
             pst = (PreparedStatement)con.prepareStatement(sqll4);
             pst.execute();
             pst = (PreparedStatement)con.prepareStatement(sqla );
             pst.execute();
             String sqlqq = "UPDATE gym.people SET  mark=0  WHERE serial='"+seriall+"'";
                    pst=(PreparedStatement) con.prepareStatement(sqlqq);
                    pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Payed Added successfully");
                        clear();
                        tablelord();
                        serial.requestFocus();


                    }
                    catch(Exception e ){
                        JOptionPane.showMessageDialog(null,e);
                    } 
    }//GEN-LAST:event_save1ActionPerformed

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel =(DefaultTableModel)tdetails.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex=tdetails.getSelectedRow();
       
       
        
       

    }//GEN-LAST:event_tdetailsMouseClicked

    private void serialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialKeyPressed
        String frommm = null;
        String tooo=null;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
             String sql="SELECT * FROM gym.people where serial='"+serial.getText()+"'";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             if(rs.next()){
                 name.setText(rs.getString("name"));
                 phone.setText(rs.getString("phone"));
                 days.setText(rs.getString("mark"));
                 count = Integer.parseInt(rs.getString("mark"));
               }
             
             String sqll="SELECT * FROM gym.pay where serial='"+serial.getText()+"' order by id DESC";
             pst=(PreparedStatement) con.prepareStatement(sqll);
             rs=pst.executeQuery();
             if(rs.next()){
                 cmsport.setSelectedItem(rs.getString("sport"));
                 frommm=rs.getString("fromm");
                 tooo=rs.getString("too");
                 
             }
             String sqlll="SELECT * FROM gym.pay where too between '"+frommm+"' and '"+tooo+"'  AND serial='"+serial.getText()+"' ORDER BY id DESC";
             pst=(PreparedStatement) con.prepareStatement(sqlll);
             rs=pst.executeQuery();
             if(rs.next()){
                 ((JTextField)from.getDateEditor().getUiComponent()).setText(rs.getString("too"));
                 
             }
             
             
                 
                 
         } 
            catch (SQLException ex) {
             
         }
        }
    }//GEN-LAST:event_serialKeyPressed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed
        clear();
        tablelord();
        serial.requestFocus();
    }//GEN-LAST:event_save3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmsport;
    private javax.swing.JComboBox cmtype;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField days;
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField price;
    private javax.swing.JButton save1;
    private javax.swing.JButton save3;
    private javax.swing.JTextField serial;
    private javax.swing.JLabel serialid;
    private javax.swing.JTable tdetails;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
public void tablelord()
    {
        try {
            String sqll = "SELECT * FROM gym.pay where date1 = '"+datee+"' ORDER BY id DESC";
              pst=(PreparedStatement) con.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails.getModel(); 
                model.setRowCount(0);
              int x = 1;
                while (rs.next())
                {
                    Object row[] = {
                       rs.getString("serial"),
                       rs.getString("name"),
                       rs.getString("sport"),
                       rs.getString("type"),
                       rs.getString("amount"),
                       rs.getString("fromm"),
                       rs.getString("too")
                       
                      
                        
                        
                                };
                    model.addRow(row);
                    x++;
                    
                }
                if(x>=11)
                {
                }
                else
                {
                for(int z = x ;z<13;z++)
                {
                 Object rowData[] = {
                       "", "", "","","",
                       };
                model.addRow(rowData);
                }
        }
        }
        catch (SQLException ex) {
            
        }
    }
    
    
    public void clear()
{
    name.setText("");
    phone.setText("");
    serial.setText("");
    cmsport.setSelectedIndex(0);
    cmtype.setSelectedIndex(0);
    price.setText("");
    ((JTextField)to.getDateEditor().getUiComponent()).setText("");
    ((JTextField)from.getDateEditor().getUiComponent()).setText(datee);
    
}
    public void sports()
   {
        try {
             String sql="SELECT name  FROM gym.sports order by name ";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                String name = rs.getString("name");
                
                cmsport.addItem(name);
  
             }

         } catch (SQLException ex) {
             
         }
   }
public void comboxfromcombo1()
      {
                   cmtype.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                JComboBox cmitemm = (JComboBox) event.getSource();
                Object item = event.getItem();
                if(cmtype.getSelectedItem().toString().equals("Month"))
                {
                    try {
             String sql="SELECT * FROM gym.sports where name='"+cmsport.getSelectedItem().toString()+"'";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                 price.setText(rs.getString("price"));
              
              }
             try {    

        Date date1;
        date1 = new SimpleDateFormat("yyyy-M-dd").parse(((JTextField)from.getDateEditor().getUiComponent()).getText());
        System.out.println(date1);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-M-dd");     
        Calendar cal  = Calendar.getInstance();
                      cal.setTime(date1);
                        cal.add(Calendar.DATE, (30));
                        String expDateString = sdf.format(cal.getTime());
                       ((JTextField)to.getDateEditor().getUiComponent()).setText(expDateString);
     }catch (ParseException ex) {
     } 

         } catch (SQLException ex) {
             
         }
                }
                if(cmtype.getSelectedItem().toString().equals("Half month"))
                {
                    try {
             String sql="SELECT * FROM gym.sports where name='"+cmsport.getSelectedItem().toString()+"'";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                 price.setText(rs.getString("half"));
              
              }
             try {    

        Date date1;
        date1 = new SimpleDateFormat("yyyy-M-dd").parse(((JTextField)from.getDateEditor().getUiComponent()).getText());
        System.out.println(date1);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-M-dd");     
        Calendar cal  = Calendar.getInstance();
                      cal.setTime(date1);
                        cal.add(Calendar.DATE, (15));
                        String expDateString = sdf.format(cal.getTime());
                       ((JTextField)to.getDateEditor().getUiComponent()).setText(expDateString);
     }catch (ParseException ex) {
     } 

         } catch (SQLException ex) {
             
         }
                }
                        
                 
         }
        });
       
      }
public void comboxfromcombo2()
      {
                   cmsport.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                JComboBox cmitemm = (JComboBox) event.getSource();

                Object item = event.getItem();
                
                 price.setText("");
                 cmtype.setSelectedIndex(0);
         }
        });
       
      }
}
